Move trigger prefix from ";" to ":"

diff --git a/match/shell.yml b/match/shell.yml
--- a/match/shell.yml
+++ b/match/shell.yml
@@ -1,85 +1,51 @@
 matches:
 
-  - trigger: ";ip"
+  - trigger: ":ip"
     replace: "curl ifconfig.io && curl ifconfig.me"
 
-  - trigger: ";path"
+  - trigger: ":path"
     replace: 'echo $PATH | tr ":" "\n"'
 
-  - trigger: ";install-docker"
+  - trigger: ":install-docker"
     replace: "curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh"
 
-  - trigger: ";install-just"
+  - trigger: ":install-just"
     replace: "curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin && curl -O https://raw.githubusercontent.com/SamEdwardes/posit-justfile/main/justfile"
 
-  - trigger: ";posit-justfile"
+  - trigger: ":posit-justfile"
     replace: "curl -O https://raw.githubusercontent.com/SamEdwardes/posit-justfile/main/justfile"
 
-  - trigger: ";ll"
+  - trigger: ":ll"
     replace: "alias ll='ls -la'"
 
-  - trigger: ";heredoc"
+  - trigger: ":bash-init"
+    replace: |
+      #!/bin/env bash
+      DEBIAN_FRONTEND=noninteractive
+
+      # n bash, unless you declare otherwise, an unset variable is used as an
+      # empty string. This is very dangerous in case of typo, as the badly typed
+      # variable will not be reported, and it will be evaluated as empty. use
+      set -o nounset
+
+      # fail on error
+      set -e
+
+      # Redirect stdout and stderr to a log file
+      # exec > ~/ubuntu/script.logs 2>&1
+
+
+  - trigger: ":heredoc"
     replace: |
       tee file <<EOF
 
       EOF
 
-  - trigger: ";sh-init"
-    replace: |
-      #!/bin/bash
-      print_new_section() {
-        echo ""
-        echo "-----------------------------------------------------------------"
-        echo "$1"
-        echo "-----------------------------------------------------------------"
-      }
-
-      # ------------------------------------------------------------------------
-      # Install system deps
-      # ------------------------------------------------------------------------
-      print_new_section "Installing system deps"
-      sudo apt-get update
-      sudo apt-get install -y build-essential
-
-      # ------------------------------------------------------------------------
-      # Install docker
-      # ------------------------------------------------------------------------
-      print_new_section "Installing Docker"
-      curl -fsSL https://get.docker.com -o get-docker.sh
-      sudo sh ./get-docker.sh
-
-      # ------------------------------------------------------------------------
-      # Install GitHub CLI
-      # ------------------------------------------------------------------------
-      print_new_section "Installing GitHub CLI"
-      type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
-      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
-        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
-        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-        && sudo apt update \
-        && sudo apt install gh -y
-
-      # ------------------------------------------------------------------------
-      # Install nvim
-      # ------------------------------------------------------------------------
-      print_new_section "Installing NeoVim"
-      curl -sSfLJ https://github.com/SamEdwardes/neovim-config/raw/main/setup.sh | bash -s --
-
-      # ------------------------------------------------------------------------
-      # Install homebrew
-      # ------------------------------------------------------------------------
-      NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-      (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> "$HOME/.profile"
-      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-      brew install gcc
-
-      # ------------------------------------------------------------------------
-      # Install Starship
-      # ------------------------------------------------------------------------
-      print_new_section "Installing Starship"
-      curl -sS https://starship.rs/install.sh -o starship_installer.sh
-      chmod +x starship_installer.sh
-      sudo ./starship_installer.sh --yes
-      echo 'eval "$(starship init bash)"' >> "$HOME/.bashrc"
-      rm starship_installer.sh
-      eval "$(starship init bash)"
+  - trigger: ":bootstrap"
+    replace: "{{output}}"
+    vars:
+      - name: output
+        type: shell
+        params:
+          cmd: |
+            gh gist view ab477cf77cceb89f34fa3e012effd72e --raw | grep '#!/bin/env bash' -A 9999
